### ISSUE TITLE
Machine specs and training time for this model

### ISSUE THREAD

**Issue by xvtyzn** [DennisGankin/species-aware-DNA-LM#1]
Hi,

Thank you for your great results and for publishing your code.
My question is about the training time and spec of the machine for training.

I have read your paper but could not find the specs of the machine used to train this DNA language model and the training time.
I think it is probably less expensive than the fine tuning of DNA-BERT.
Can you tell me how long it took to train the model?

Best,

Keigo

**Comment by DennisGankin** [comment]
Hi Keigo,

Thank you for your question.
With four NVIDIA A40 GPUs, 16 cores, and 64GB RAM, we trained the model in ~23 hours (50 epochs).

Best, 
Dennis
